### ISSUE TITLE
Please publish a new/current version to https://rubygems.org/

### ISSUE THREAD

**Issue by aramprice** [cloudfoundry/omniauth-uaa-oauth2#21] opened 2022-09-15 23:57 UTC
The last version published to https://rubygems.org/gems/omniauth-uaa-oauth2 was in 2018

**Comment by rkoster** [comment] 2023-04-26 18:10
@strehle do you think it would make sense to move this repo over to github actions, like was done for [cf-uaa-lib](https://github.com/cloudfoundry/cf-uaa-lib/tree/master/.github)?

**Comment by strehle** [comment] 2023-04-27 06:12
@rkoster added gh file, but you or someone from VMware needs to add credentials for rubygems

**Comment by aramprice** [comment] 2023-04-27 18:03
@strehle / @rkoster it looks like the owners of the [gem on RubyGems.org](https://rubygems.org/gems/omniauth-uaa-oauth2) are [Dr. Nic](https://rubygems.org/profiles/drnic), and [gramos](https://rubygems.org/profiles/gramos).

Perhaps it would be worth asking if the [CF RubyGems user](https://rubygems.org/profiles/cf) could be added as an owner of the Gem?

**Comment by rkoster** [comment] 2023-04-27 18:30
@drnic would you be able to add the [cf ruby gems user](https://rubygems.org/profiles/cf) as an owner to the [omniauth-uaa-oauth2 gem](https://rubygems.org/gems/omniauth-uaa-oauth2)?

**Comment by drnic** [comment] 2023-05-02 03:39
Done.

$ gem owner omniauth-uaa-oauth2 -a cf
cf was added as an unconfirmed owner. Ownership access will be enabled
after the user clicks on the confirmation mail sent to their email.
Owners for gem: omniauth-uaa-oauth2
- gramos
- drnic

**Comment by aramprice** [comment] 2023-05-02 21:27
Thanks @drnic !

**Comment by strehle** [comment] 2023-05-10 05:27
@rkoster can you add RUBYGEMS_AUTH_TOKEN to this repo , then this should work.
https://github.com/cloudfoundry/omniauth-uaa-oauth2/actions/workflows/gem-push.yml

**Comment by rkoster** [comment] 2023-05-11 10:02
secret has been added.

**Comment by strehle** [comment] 2023-05-11 10:21
@rkoster Thanks, @aramprice close this now since https://rubygems.org/gems/omniauth-uaa-oauth2/versions/1.1.1 deployed

**Closed by strehle** 2023-05-11 10:21 UTC
